the_list = ['Mountains','Cities','Countries','Rides','Sunset','Sunrises']
print(the_list)
print(sorted(the_list))
print(sorted(the_list,reverse=True))
print('\n',the_list,'\n')
the_list.sort()
print(the_list)
the_list.sort(reverse=True)
print(the_list)
the_list.reverse()
print(the_list)
the_list.pop()
print('\n',the_list)
the_list.remove('Cities')
print(the_list)
the_list.append('Sunset')
print(the_list)
the_list.index('Sunset')
print(the_list.index('Sunset'))
print(len(the_list))
del the_list[1]
print(the_list)
the_list.insert(0,'Nani ka ghar')
print(the_list)